"""COVERAGE.md, docs/FINDINGS.md and one static HTML page per ISIN (inline SVG, deterministic, no external assets)."""
from __future__ import annotations

import csv
import html
import math
from pathlib import Path

from . import history as Hs
from .sources import MANUAL, REGISTRY

CSS = """:root{--bg:#fff;--fg:#1b1f24;--mut:#5b6570;--line:#d9dee3;--band1:#c9dcf2;--band2:#8fb6e3;--med:#1f5fa8;--bad:#b3261e;--ok:#1e7b34}
@media (prefers-color-scheme: dark){:root{--bg:#15181c;--fg:#e6e9ec;--mut:#9aa4ae;--line:#2c3239;--band1:#1f3550;--band2:#2f5686;--med:#8fbaf0;--bad:#f2867e;--ok:#7fd18f}}
body{background:var(--bg);color:var(--fg);font:14px/1.45 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;margin:0 auto;max-width:1100px;padding:16px}
table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;font-size:12.5px}th,td{border-bottom:1px solid var(--line);padding:3px 6px;text-align:right}
th:first-child,td:first-child{text-align:left}.wrap{overflow-x:auto}.mut{color:var(--mut)}.bad{color:var(--bad)}.ok{color:var(--ok)}
h1{font-size:20px}h2{font-size:16px;margin-top:28px}code{font-size:12px}"""


def _read(p: Path) -> list[dict]:
    if not p.exists():
        return []
    with open(p, newline="", encoding="utf-8") as h:
        return list(csv.DictReader(h))


def coverage_rows(run) -> list[dict]:
    gaps = _read(run.out / "gaps.csv")
    ye = _read(run.out / "yearend_reconciliation.csv")
    gate = {r["isin"]: r for r in _read(run.out / "reproduction_gate.csv")}
    champ = {r["isin"]: r for r in _read(run.out / "champion_models.csv")}
    out = []
    for isin, s in REGISTRY.items():
        rows = Hs.load(run.out, isin)
        st = [str(r["parse_status"]) for r in rows]
        g = [x for x in gaps if x["isin"] == isin and x["status"] == "MISSING"]
        y = [x for x in ye if x["isin"] == isin]
        out.append({"isin": isin, "ticker": s.ticker.replace("_", " "), "n": len(rows),
                    "first": rows[0]["payment_date"] if rows else "", "last": rows[-1]["payment_date"] if rows else "",
                    "gaps": len(g), "gap_list": ", ".join(x["expected_ipd"] for x in g),
                    "ok": sum(x.startswith("ok") for x in st), "derived": sum(x.startswith("DERIVED") for x in st),
                    "partial": sum(x.startswith("PARTIAL") for x in st),
                    "review": sum(x.startswith(("review", "FAIL", "ERROR")) for x in st),
                    "yearend": f"{sum(x['result'] == 'TIED' for x in y)} tied / {sum(x['result'] == 'BREAK' for x in y)} break / {len(y)}",
                    "gate": gate.get(isin, {}).get("gate_status", ""),
                    "model": champ.get(isin, {}).get("status", ""),
                    "manual": isin in MANUAL})
    return out


def write_coverage(run, cov):
    lines = ["# Coverage (issuer-reported IPDs)", "",
             f"Generated by `python -m rmbs.run` (valuation date {run.vdate}). Source of every row: `source_url` in "
             "`out/<ISIN>_<ticker>.csv`. Gaps = expected IPDs (prospectus calendar, first IPD to the latest published "
             "report) with no filing held; full list in `out/gaps.csv`.", "",
             "| ISIN | ticker | IPDs | first | last | gaps | ok | derived | partial | review | year-ends (tied/break/total) | gate | model |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for c in cov:
        lines.append(f"| {c['isin']} | {c['ticker']} | {c['n']} | {c['first']} | {c['last']} | {c['gaps']} | {c['ok']} | "
                     f"{c['derived']} | {c['partial']} | {c['review']} | {c['yearend']} | {c['gate']} | {c['model']} |")
    lines += ["", "## Gap lists", ""]
    for c in cov:
        if c["gap_list"]:
            gl = c["gap_list"].split(", ")
            lines.append(f"- **{c['ticker']}** ({len(gl)}): {', '.join(gl[:60])}{' ...' if len(gl) > 60 else ''}")
    stage = _read(run.out / "stage_status.csv") or run.stage_status
    lines += ["", "## Last run", ""] + [f"- {s['stage']}: {s['status']} - {s['detail']}" for s in run.stage_status]
    (run.root / "COVERAGE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def svg_fan(fan: list[dict], metric: str, title: str, w=640, h=220) -> str:
    pts = [r for r in fan if r["metric"] == metric]
    if not pts:
        return "<p class=mut>No fan chart (no model could be fitted).</p>"
    ys = [float(r[k]) for r in pts for k in ("p5", "p95")]
    lo, hi = min(ys), max(ys) or 1.0
    n = len(pts)
    px = lambda i: 50 + (w - 70) * i / max(n - 1, 1)
    py = lambda v: 10 + (h - 40) * (1 - (float(v) - lo) / ((hi - lo) or 1))
    def band(a, b):
        up = " ".join(f"{px(i):.1f},{py(r[a]):.1f}" for i, r in enumerate(pts))
        dn = " ".join(f"{px(i):.1f},{py(r[b]):.1f}" for i, r in reversed(list(enumerate(pts))))
        return up + " " + dn
    med = " ".join(f"{px(i):.1f},{py(r['p50']):.1f}" for i, r in enumerate(pts))
    ticks = "".join(f'<text x="{px(i):.1f}" y="{h - 8}" font-size="10" text-anchor="middle" fill="var(--mut)">{pts[i]["payment_date"][:7]}</text>'
                    for i in range(0, n, max(1, n // 6)))
    ylab = "".join(f'<text x="46" y="{py(v) + 3:.1f}" font-size="10" text-anchor="end" fill="var(--mut)">{v / 1e6:,.1f}m</text>'
                   for v in (lo, (lo + hi) / 2, hi))
    return (f'<figure><figcaption>{html.escape(title)}</figcaption><svg viewBox="0 0 {w} {h}" width="100%" role="img" '
            f'aria-label="{html.escape(title)}"><polygon points="{band("p5", "p95")}" fill="var(--band1)"/>'
            f'<polygon points="{band("p25", "p75")}" fill="var(--band2)"/><polyline points="{med}" fill="none" '
            f'stroke="var(--med)" stroke-width="2"/>{ticks}{ylab}</svg></figure>')


def _num(v, nd=2):
    try:
        f = float(v)
    except (TypeError, ValueError):
        return html.escape(str(v))
    return "" if math.isnan(f) else f"{f:,.{nd}f}"


def write_isin_page(run, isin, cov):
    s = REGISTRY[isin]
    rows = Hs.load(run.out, isin)
    gate = next((r for r in _read(run.out / "reproduction_gate.csv") if r["isin"] == isin), {})
    champ = next((r for r in _read(run.out / "champion_models.csv") if r["isin"] == isin), {})
    fan = _read(run.out / "uncertainty" / f"{isin}.csv")
    bbg = [r for r in _read(run.out / "bbg_vs_model.csv") if r["isin"] == isin]
    scores = _read(run.out / "model_scores" / f"{isin}.csv")
    c = next(x for x in cov if x["isin"] == isin)
    cft_rank = _read(run.out / "cft" / f"{isin}_ranking.csv")[:10]
    cft_sum = next((r for r in _read(run.out / "cft" / "summary.csv") if r["isin"] == isin), {})
    cft_html = "<p class=mut>Not ranked (no filed state).</p>" if not cft_rank else (
        f"<p>{html.escape(cft_sum.get('status', ''))}; {cft_sum.get('n_configs', '')} configurations; equivalence class "
        f"{cft_sum.get('equivalence_class_size', '')} (WAL {_num(cft_sum.get('equiv_wal_min'))}-{_num(cft_sum.get('equiv_wal_max'))}y); "
        f"filing facts used: {html.escape(cft_sum.get('filed_facts_used', ''))}; out-of-sample Spearman(S, error) "
        f"{_num(cft_sum.get('criterion_mean_spearman'))}, smoothest beats naive {cft_sum.get('criterion_smoothest_beats_naive', '')}</p>"
        "<div class=wrap><table><tr><th>#</th><th>S</th><th>prepay</th><th>default</th><th>sev</th><th>lag</th><th>call</th>"
        "<th>trigger</th><th>WAL</th><th>DM@ref</th></tr>" + "".join(
            f"<tr><td>{r['rank']}</td><td>{_num(r['S'], 3)}</td><td>{html.escape(r['prepay'])}</td><td>{html.escape(r['default'])}</td>"
            f"<td>{r['severity']}</td><td>{r['lag_m']}</td><td>{r['call']}</td><td>{r['trigger']}</td><td>{_num(r['wal_years'])}</td>"
            f"<td>{_num(r['dm_bp_at_ref'], 1)}</td></tr>" for r in cft_rank) + "</table></div>")
    trs = "".join(f"<tr><td>{r['payment_date']}</td><td>{_num(r['beg_balance'])}</td><td>{_num(r['principal_paid'])}</td>"
                  f"<td>{_num(r['end_balance'])}</td><td>{_num(r['interest_paid'])}</td><td>{_num(r['coupon_rate'], 5)}</td>"
                  f"<td>{html.escape(str(r['parse_status'])[:40])}</td><td><a href=\"{html.escape(str(r['source_url']))}\">src</a></td></tr>"
                  for r in rows)
    top = sorted({(r["candidate"], r["S"]) for r in scores}, key=lambda x: float(x[1]))[:10]
    note = "" if str(champ.get("status", "")).startswith("CHAMPION") else \
        "<p class=bad>No accepted model: the fan chart shows the best-scoring candidate as a <b>scenario</b>, not a forecast.</p>"
    body = f"""<h1>{html.escape(s.deal)} &middot; {html.escape(isin)} ({html.escape(s.series or '?')})</h1>
<p class=mut>{c['n']} IPDs ({c['first']} &rarr; {c['last']}); gaps {c['gaps']}; ok {c['ok']}, derived {c['derived']}, partial {c['partial']}, review {c['review']}; year-ends {c['yearend']}.</p>
<h2>Reproduction gate</h2><p>Status <b>{html.escape(gate.get('gate_status', ''))}</b> &mdash; G1 {gate.get('G1', '')} · G2 {gate.get('G2', '')} · G3 {gate.get('G3', '')} · G4 {gate.get('G4', '')} · G5 {gate.get('G5', '')} · G6 {gate.get('G6', '')}</p><p class=mut>{html.escape(gate.get('detail', ''))}</p>
<h2>Model selection</h2><p>Status <b>{html.escape(champ.get('status', ''))}</b>; best candidate <code>{html.escape(champ.get('cpr_model', ''))} | {html.escape(champ.get('call', ''))}</code>; gates {html.escape(champ.get('gates_passed', ''))}</p>{note}
<div class=wrap><table><tr><th>candidate</th><th>S</th></tr>{''.join(f'<tr><td>{html.escape(a)}</td><td>{_num(b, 3)}</td></tr>' for a, b in top)}</table></div>
{svg_fan(fan, 'balance', 'Projected class balance, p5-p95 / p25-p75 / median (EUR)')}
<h2>CFT configurations ranked by smoothness</h2>{cft_html}
<h2>Bloomberg comparison</h2><p>{'; '.join(html.escape(b['status'] + ' ' + b['metric']) for b in bbg)}</p>
<h2>Payment history (issuer filings)</h2><div class=wrap><table><tr><th>IPD</th><th>beg</th><th>principal</th><th>end</th><th>interest</th><th>coupon</th><th>status</th><th></th></tr>{trs}</table></div>"""
    page = f"<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>{html.escape(s.ticker)}</title><style>{CSS}</style></head><body>{body}</body></html>\n"
    run.reports.mkdir(parents=True, exist_ok=True)
    (run.reports / f"{isin}.html").write_text(page, encoding="utf-8")


def write_index(run, cov):
    trs = "".join(f"<tr><td><a href=\"{c['isin']}.html\">{c['isin']}</a></td><td>{html.escape(c['ticker'])}</td><td>{c['n']}</td>"
                  f"<td>{c['first']}</td><td>{c['last']}</td><td>{c['gaps']}</td><td>{c['ok']}</td><td>{c['derived']}</td>"
                  f"<td>{c['review']}</td><td>{html.escape(c['gate'])}</td><td>{html.escape(c['model'])}</td></tr>" for c in cov)
    page = (f"<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>"
            f"<title>RMBS coverage</title><style>{CSS}</style></head><body><h1>RMBS payment history &amp; model selection</h1>"
            f"<p class=mut>Valuation date {run.vdate}. Filings are the state; Bloomberg is a benchmark.</p><div class=wrap><table>"
            f"<tr><th>ISIN</th><th>ticker</th><th>IPDs</th><th>first</th><th>last</th><th>gaps</th><th>ok</th><th>derived</th>"
            f"<th>review</th><th>gate</th><th>model</th></tr>{trs}</table></div></body></html>\n")
    (run.reports / "index.html").write_text(page, encoding="utf-8")


def write_findings(run):
    """Auto section of docs/FINDINGS.md (between markers); the curated section above it is preserved."""
    p = run.root / "docs" / "FINDINGS.md"
    head = p.read_text(encoding="utf-8").split("<!-- AUTO -->")[0] if p.exists() else "# Findings\n\n"
    ye = [r for r in _read(run.out / "yearend_reconciliation.csv") if r["result"] == "BREAK"]
    cal = [r for r in _read(run.out / "calendar_checks.csv") if r["result"] != "EXACT"]
    val = [r for r in _read(run.out / "validation.csv") if r["result"] in ("FAIL", "BREAK")]
    lines = ["<!-- AUTO -->", "## Automatic checks (regenerated every run)", "",
             f"- Failed row/chain checks: {len(val)}"] + [f"  - {r['isin']} {r['payment_date']} {r['check']}: {r['detail']}" for r in val[:40]]
    lines += [f"- Year-end breaks: {len(ye)}"] + [f"  - {r['isin']} {r['date']}: chain {r['chain_kEUR']} vs audited {r['checkpoint_kEUR']} kEUR ({r['source_url']})" for r in ye]
    lines += [f"- IPD calendar deviations (observed vs prospectus rule): {len(cal)}"] + [f"  - {r['isin']} {r['observed']} vs rule {r['projected']}: {r['result']}" for r in cal[:40]]
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(head.rstrip() + "\n\n" + "\n".join(lines) + "\n", encoding="utf-8")


def write_zip(run) -> int:
    """RMBS_reports_ALL.zip: every source PDF under reports/, the text captures, the manifest and the download log.
    Fixed timestamps + sorted entries -> byte-stable archive."""
    import zipfile
    files = sorted(run.reports.rglob("*.pdf")) + sorted((run.root / "captures").rglob("*.txt"))
    extra = [run.root / "filing_locations.csv", run.root / "download_log.csv"]
    n = 0
    with zipfile.ZipFile(run.root / "RMBS_reports_ALL.zip", "w", zipfile.ZIP_DEFLATED) as z:
        for p in files + [e for e in extra if e.exists()]:
            zi = zipfile.ZipInfo(str(p.relative_to(run.root)), date_time=(2026, 1, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(zi, p.read_bytes())
            n += p.suffix == ".pdf"
    return n


def write_all(run):
    cov = coverage_rows(run)
    write_coverage(run, cov)
    for isin in REGISTRY:
        write_isin_page(run, isin, cov)
    write_index(run, cov)
    write_findings(run)
    write_zip(run)
